name: Android Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxpkg --global
          haxelib run hxpkg setup --global
          hxpkg install
          haxelib install SStas-An
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools

      - name: Configure Lime Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK ${{ steps.setup-ndk.outputs.ndk-path }}
          haxelib run lime config JAVA_HOME $JAVA_HOME

      - name: Build APK
        run: haxelib run lime build android -final

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NightmareVision-Android
          path: export/release/android/bin/app/build/outputs/apk/**/*.apk
          if-no-files-found: error