name: Android Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          # Bibliotecas Base
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib run lime setup
          
          # Bibliotecas do Motor (Psych/NVM)
          haxelib install flixel-addons --quiet
          haxelib install flixel-ui --quiet
          haxelib install flxanimate --quiet
          haxelib install hscript-iris --quiet
          
          # Bibliotecas Nativas (Git) - Crucial para não dar "Type not found"
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git hxvlc https://github.com/MAJigsaw77/hxvlc
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools

      - name: Configure Lime Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK ${{ steps.setup-ndk.outputs.ndk-path }}
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Build APK
        run: |
          haxelib run lime build android -debug -clean -DHXCPP_COMPILE_THREADS=4

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NightmareVision-Android
          path: export/debug/android/bin/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error